# Generated by Django 3.0.1 on 2020-03-28 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientpayment',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
