# Generated by Django 3.0.1 on 2020-03-07 10:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientpayment',
            name='payment_time',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='payment_time',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
