# Generated by Django 3.0.1 on 2020-02-15 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_clientpayment_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientpayment',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='clientpayment',
            name='payment_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='payment_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='payment_type',
            field=models.CharField(choices=[('i', 'Payment From Supplier'), ('o', 'Payment To Supplier')], default='i', max_length=1),
        ),
    ]
