# Generated by Django 3.0.1 on 2020-02-15 20:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_auto_20200216_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientpayment',
            name='payment_time',
            field=models.DateField(default=datetime.date(2020, 2, 16)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='payment_time',
            field=models.DateField(),
            preserve_default=False,
        ),
    ]
