# Generated by Django 3.1 on 2022-12-11 19:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import sabzi_mandi.models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('is_draft', models.BooleanField(default=False)),
                ('bill_date', models.DateField()),
                ('balance', sabzi_mandi.models.CustomFloatField(default=0)),
                ('billed_amount', sabzi_mandi.models.CustomFloatField(default=0)),
                ('other_expence', models.JSONField(default='{}')),
                ('Supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierBillDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(choices=[('k', 'KG'), ('i', 'Count')], max_length=1)),
                ('rate', sabzi_mandi.models.CustomFloatField()),
                ('item_count', sabzi_mandi.models.CustomFloatField()),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.supplierbill')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.item')),
            ],
        ),
    ]
