# Generated by Django 3.0.1 on 2020-02-16 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='current_balance',
            field=models.IntegerField(default=0),
        ),
    ]
