# Generated by Django 3.0.1 on 2020-02-09 17:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('payments', '0001_initial'),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('bill_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('is_draft', models.BooleanField(default=False)),
                ('balance', models.IntegerField(default=0)),
                ('billed_amount', models.IntegerField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.ClientPayment')),
            ],
        ),
        migrations.CreateModel(
            name='BillDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(choices=[('k', 'KG'), ('i', 'Item')], max_length=1)),
                ('rate', models.IntegerField()),
                ('item_count', models.IntegerField()),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_bills.ClientBill')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.Item')),
            ],
        ),
    ]
