# Generated by Django 3.0.1 on 2020-06-05 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_bills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billdetail',
            name='item_count',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='billdetail',
            name='rate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='clientbill',
            name='billed_amount',
            field=models.FloatField(default=0),
        ),
    ]
