# Generated by Django 3.0.1 on 2020-06-06 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_bills', '0002_auto_20200605_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientbill',
            name='balance',
            field=models.FloatField(default=0),
        ),
    ]
