# Generated by Django 3.0.1 on 2020-06-06 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientledger',
            name='balance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='clientledger',
            name='bill_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='clientledger',
            name='payment_amount',
            field=models.FloatField(default=0),
        ),
    ]
