# Generated by Django 3.0.1 on 2020-07-05 15:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import sabzi_mandi.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('name', models.CharField(max_length=200)),
                ('cnic', models.CharField(blank=True, max_length=16, null=True)),
                ('phone', models.CharField(blank=True, max_length=16, null=True)),
                ('address', models.CharField(blank=True, max_length=264, null=True)),
                ('opening_balance', sabzi_mandi.models.CustomFloatField()),
                ('current_balance', sabzi_mandi.models.CustomFloatField()),
                ('identifier', models.IntegerField()),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.Shop')),
            ],
            options={
                'unique_together': {('shop', 'name'), ('shop', 'identifier')},
            },
        ),
    ]
