# Generated by Django 3.0.1 on 2020-06-05 18:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
