# Generated by Django 3.0.1 on 2020-02-08 18:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dukan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('payment_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('paymentType', models.CharField(choices=[('i', 'In'), ('o', 'Out')], max_length=1)),
                ('description', models.TextField(blank=True, null=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dukan.Supplier')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
