# Generated by Django 3.0.1 on 2020-01-01 20:44

from django.db import migrations, models
import dukan.models


class Migration(migrations.Migration):

    dependencies = [
        ('dukan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='logo_thumbnail',
            field=models.ImageField(default='', editable=False, upload_to='shops_thumbs/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shop',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='shops/', validators=[dukan.models.validate_file_ext]),
        ),
    ]
