# Generated by Django 3.0.1 on 2020-01-03 15:09

from django.db import migrations, models
import dukan.models


class Migration(migrations.Migration):

    dependencies = [
        ('dukan', '0002_auto_20200101_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shop',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=dukan.models.content_file_name, validators=[dukan.models.validate_file_ext]),
        ),
    ]
