# Generated by Django 3.0.1 on 2020-01-03 21:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dukan', '0003_auto_20200103_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(choices=[('k', 'KG'), ('i', 'Item')], max_length=1)),
                ('rate', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ClientBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('is_draft', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dukan.Client')),
            ],
        ),
        migrations.CreateModel(
            name='ClientPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('payment_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dukan.Client')),
            ],
        ),
        migrations.RemoveField(
            model_name='payment',
            name='client',
        ),
        migrations.DeleteModel(
            name='Bill',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.AddField(
            model_name='billdetail',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dukan.ClientBill'),
        ),
        migrations.AddField(
            model_name='billdetail',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dukan.Item'),
        ),
    ]
