# Generated by Django 3.0.1 on 2020-02-08 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dukan', '0003_auto_20200209_0309'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
