# Generated by Django 3.0.1 on 2020-01-03 21:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dukan', '0004_auto_20200104_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientbill',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
