# Generated by Django 3.0.1 on 2020-01-06 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dukan', '0005_clientbill_created_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientbill',
            name='balance',
            field=models.FloatField(default=0),
        ),
    ]
