# Generated by Django 3.0.1 on 2020-01-07 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dukan', '0006_clientbill_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='billdetail',
            name='item_count',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='billdetail',
            name='rate',
            field=models.FloatField(),
        ),
    ]
